config:
  target: 'http://localhost:3000'
  phases:
    - duration: 20
      arrivalRate: 10
scenarios:
  - flow:
      - post:
          url: '/job/submit-code'
          json:
            code: |
              def fibonacci(n):
                  a, b = 0, 1
                  result = []
                  while len(result) < n:
                      result.append(a)
                      a, b = b, a + b
                  return result

              print(fibonacci(2000))
      - get:
          url: '/job/exec-result'
          qs:
            jobId: "{{ json.result.jobId }}"
